[package]
name = "serde-error"
version = "0.1.0"
authors = ["Léo Gaspard <leo@gaspard.io>"]
license = "MIT"
categories = ["development-tools", "development-tools::debugging"]
keywords = ["error", "failure", "serde", "anyhow"]
description = "Serde (de)serializer for Error types"
repository = "https://github.com/Ekleog/serde-error"
edition = "2018"

[dependencies]
anyhow = "1.0.72"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
bincode = "1.3"
